title: Heidi Leung
#description: 3rd Yr UBC Integrated Engineering Student: Mechanical & Electrical
#logo: /assets/headshot.jpg
<img src="/assets/headshot.jpg" width="150"> 
show_downloads: false
theme: jekyll-theme-minimal
